name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "pypy-3.7"]

    steps:
  {# mark as 'raw' to prevent cookiecutter jinja from replacing the github variables #}
  {% raw %}
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
  {% endraw %}
    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH=$PATH:$HOME/.local/bin
        poetry install
    - name: Run pytest
      run: |
        poetry run pytest --cov-report=xml --cov={{ cookiecutter.project_slug }} tests
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        {% raw %}
#        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        {% endraw %}
