repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black

  - repo: https://github.com/PYCQA/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        exclude: ^.venv
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.740'  # Use the sha / tag you want to point at
    hooks:
    - id: mypy
      # for args see https://mypy.readthedocs.io/en/stable/command_line.html
      args: [
          --no-strict-optional,
          --ignore-missing-imports,
          --allow-untyped-globals
      ]
default_language_version:
    python: python3.7

