minimum_pre_commit_version: "3.0"
repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.256'
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
  files: ^src/.*\.py$
  exclude: ^tests/
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.22.0
  hooks:
  - id: check-gitlab-ci
    files: .gitlab-ci.yml
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.29.0
  hooks:
  - id: yamllint
    args: [-d relaxed]
    verbose: true
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.0.1
  hooks:
  - id: mypy
    # for args see https://mypy.readthedocs.io/en/stable/command_line.html
    args: [
      --no-strict-optional,
      --ignore-missing-imports,
      --allow-untyped-globals
    ]
