minimum_pre_commit_version: "3.0"
repos:
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.14.3
  hooks:
  - id: check-gitlab-ci
    files: .gitlab-ci.yml
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.17.0
  hooks:
  - id: yamllint
    args: [-d relaxed]
    verbose: true
- repo: https://github.com/timothycrosley/isort
  rev: 5.11.5
  hooks:
  - id: isort
    additional_dependencies: [toml]
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
- repo: https://github.com/PYCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    exclude: ^.venv
    files: ^{{ cookiecutter.project_slug }}\/.*\.py$
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.950
  hooks:
  - id: mypy
    # for args see https://mypy.readthedocs.io/en/stable/command_line.html
    args: [
      --no-strict-optional,
      --ignore-missing-imports,
      --allow-untyped-globals
    ]
- repo: https://github.com/pycqa/pydocstyle
  rev: 6.1.1
  hooks:
  - id: pydocstyle
    exclude: ^tests/
    additional_dependencies: [toml]
