minimum_pre_commit_version: "1.21"
files: ^.*\.py$
repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
    - id: isort
      additional_dependencies: [toml]
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/PYCQA/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        exclude: ^.venv
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.800
    hooks:
    - id: mypy
      # for args see https://mypy.readthedocs.io/en/stable/command_line.html
      args: [
          --no-strict-optional,
          --ignore-missing-imports,
          --allow-untyped-globals
      ]
default_language_version:
    python: python3.8

