version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
  jobs:
    post_create_environment:
    # Install poetry
    - curl -sSL https://install.python-poetry.org | python -
    # Tell poetry to not use a virtual environment
    - $HOME/.poetry/bin/poetry config virtualenvs.create false
    # Install project's dependencies
    - $HOME/.poetry/bin/poetry install
