version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
  jobs:
    post_create_environment:
    # Install poetry
    - curl -sSL https://install.python-poetry.org | python -
    # export requirements
    - $HOME/.poetry/bin/poetry export --with docs -o requirements.txt

python:
  system_packages: true
  install:
  - requirements: requirements.txt
  - method: pip
    path: .
