[tool.poetry]
name = "{{ cookiecutter.project_slug }}"
version = "{{ cookiecutter.version }}"
description = "{{ cookiecutter.project_short_description }}"
authors = ["{{cookiecutter.full_name }} <{{ cookiecutter.email }}>"]
license = "{{ cookiecutter.license }}"
readme = "README.md"
homepage = "https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.project_slug}}"
repository = "https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.project_slug}}"
documentation = "https://{{ cookiecutter.project_slug }}.readthedocs.io"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: Implementation :: PyPy"
]

[tool.poetry.dependencies]
python = "^3.7"
importlib-metadata = {version="^4.11.3", python="<3.8"}

# documentation
# Due to the way poetry (and readthedocs) handle package extras (dependencies),
# the doc dependencies must by located here, and not as dev-dependencies.
# Once poetry 1.2.0 is released, this can be solved more elegantly.
myst-parser = {version="^0.17.0", optional=true}
Sphinx = {version="^4.5.0", optional=true}
sphinx-autobuild = {version="^2021.3.14", optional=true}
sphinx-panels = {version="^0.6.0", optional=true}
sphinx-rtd-theme = {version="^1.0.0", optional=true}
sphinxcontrib-mermaid = {version="^0.7.1", optional=true}

[tool.poetry.dev-dependencies]
pytest = "^6.1"
pre-commit = "^2.8"
tox = "^3.20.1"

# deployment
twine = "^4.0.0"

[tool.poetry.extras]
docs = [
    "myst-parser",
    'Sphinx',
    'sphinx-autobuild',
    'sphinx-panels',
    'sphinx-rtd-theme',
    'sphinx-contrib-mermaid'
]

[tool.isort]
profile = "black"
multi_line_output = 3

[build-system]
requires = ["poetry-core>=1.0"]
build-backend = "poetry.core.masonry.api"
